name: run unit test on feature branch

on:
  pull_request:
    branches:
     - master
     
jobs:
  run_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: run with Maven
        run: mvn test
       
   

