on:
  push:
    branches:
      - "**" # This will run on all branches and must be quoted to be handled by YAML

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Run tests with Maven
        run: mvn test
      # Handle remote server chromedriver

