# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches:
      - master
      - issue-*
  push:
    branches:
      - master
      - issue-*

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '18' # Use a valid Java version (e.g., 11)
          distribution: 'adopt'
          cache: maven

      - name: Build the Project
        run: mvn clean install -DskipTests

      - name: Upload target folder
        uses: actions/upload-artifact@v4
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
            ${{ github.workspace }}/reports