name: nightly build at 11pm

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  nightly_build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: maven
      - name: Run Test Cases Using Maven
        run: mvn clean test
