name: Regression test workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Out Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: maven

      - name: Run Test Cases Using Maven
        run: mvn test -PErrorValidation -DBrowserName=chrome

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate Allure Report
        run: allure generate --clean

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
